spring:
  application:
    name: laa-amend-a-claim
    version: 1.0.0
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: ${AZURE_CLIENT_ID}
            client-secret: ${AZURE_CLIENT_SECRET}
            scope: openid, profile, email
            redirect-uri: ${BASE_URL_HOMEPAGE}/login/oauth2/code/azure
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
          graph:
            client-id: ${AZURE_CLIENT_ID}
            client-secret: ${AZURE_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: https://graph.microsoft.com/.default
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0
            token-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            jwk-set-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/discovery/v2.0/keys
          graph:
            token-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/oauth2/v2.0/token
  data:
    redis:
      url: ${REDIS_URL}
  servlet:
    multipart:
      max-file-size: 10MB

sentry:
  enabled: ${SENTRY_ENABLED:true}
  dsn: ${SENTRY_DSN:}
  environment: ${SENTRY_ENVIRONMENT:}
  logs:
    enabled: true
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
claims-api:
  url: ${CLAIMS_API}
  access-token: ${CLAIMS_TOKEN}
microsoft-graph-api:
  url: https://graph.microsoft.com
provider-api:
  url: ${PROVIDER_DETAILS_API_URL}
  access-token: ${PROVIDER_DETAILS_API_ACCESS_TOKEN}
fee-scheme-api:
  url: ${FEE_SCHEME_PLATFORM_API_URL}
  access-token: ${FEE_SCHEME_PLATFORM_API_ACCESS_TOKEN}
submission:
  high-value-assessment-limit: 50000
app:
  feedback-url: ${FEEDBACK_URL}
  laa-url: ${LAA_URL}
  email: AmendaBulkClaimTeam@justice.gov.uk

maintenance:
  banner-title: ${OUTAGE_BANNER_TITLE:Outage Scheduled}
  disable-at-time: ${OUTAGE_BANNER_DISABLE_AT_TIMESTAMP:2026-06-01T00:00:00Z}
  outage-banner-message: ${OUTAGE_BANNER_MESSAGE:System maintenance scheduled.}

feature-flags:
  is-bulk-upload-enabled: ${IS_BULK_UPLOAD_ENABLED:false}
  is-claim-amendment-enabled: ${IS_CLAIM_AMENDMENT_ENABLED:false}
  is-fsp-history-enabled: ${IS_FSP_HISTORY_ENABLED:false}
management:
  server:
    port: 8282
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

server:
  servlet:
    session:
      cookie:
        name: AACSESSION
        same-site: lax
      tracking-modes: cookie

# ECS structured logging
logging:
  level:
    root: ${ROOT_LOGGING_LEVEL:info}
    org.springframework: ${SPRING_LOGGING_LEVEL:info}
    uk.gov.justice.laa.payments.amend: ${APP_LOGGING_LEVEL:info}
  structured:
    format:
      console: ecs
    ecs:
      service:
        name: ${spring.application.name:default}
        version: ${spring.application.version:default}
        environment: ${spring.profiles.active:default}
        node_name: ${HOSTNAME:unknown}

---
spring:
  config:
    activate:
      on-profile: local | docker

server:
  port: 8090
management:
  server:
    port: 8190

logging:
  structured:
    format:
      console: # disables structured logging locally
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr{faint} %clr([%15.15t]){faint} %clr([%X{traceId:-},%X{spanId:-}]){yellow} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
---
spring:
  config:
    activate:
      on-profile: local
      
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  web:
    resources:
      static-locations: file:build/resources/main/static/
      cache:
        period: 0
---
spring:
  config:
    activate:
      on-profile: ephemeral
