package uk.gov.justice.laa.amend.claim.models.enums;

import uk.gov.justice.laa.amend.claim.viewmodels.viewfield.FieldOption;

public enum ExemptionCriteriaSatisfied implements FieldOption {
  DOMESTIC_ABUSE_INJUNCTION_OR_PROTECTIVE_ORDER("DV001"),
  DOMESTIC_ABUSE_RELEVANT_CONVICTION_CAUTION_OR_BIND_OVER("DV002"),
  DOMESTIC_ABUSE_ON_GOING_CRIMINAL_PROCEEDINGS_FOR_A_DOMESTIC_ABUSE_OFFENCE_BY_THE("DV003"),
  DOMESTIC_ABUSE_VICTIM_HAS_BEEN_REFERRED_TO_A_MULTI_AGENCY_RISK_ASSESSMENT_CONFER("DV004"),
  DOMESTIC_ABUSE_THERE_HAS_BEEN_A_FINDING_OF_FACT_IN_THE_FAMILY_COURTS_OF_DOMESTIC("DV005"),
  DOMESTIC_ABUSE_UNDERTAKING_FROM_THE_RESPONDENT("DV006"),
  DOMESTIC_ABUSE_A_DEFINED_APPROPRIATE_HEALTH_PROFESSIONAL_REPORT_LETTER("DV008"),
  DOMESTIC_ABUSE_REFERRAL_TO_DOMESTIC_ABUSE_SUPPORT_SERVICE("DV011"),
  DOMESTIC_ABUSE_EVIDENCE_OF_ECONOMIC_FINANCIAL_ABUSE("DV012"),
  DOMESTIC_ABUSE_LETTER_OR_REPORT_FROM_A_DA_SUPPORT_ORGANISATION_RELATED_TO_A_VICT("DV013"),
  DOMESTIC_ABUSE_LETTER_FROM_A_LOCAL_AUTHORITY_OR_HOUSING_ASSOCIATION_CONFIRMING_T("DV014"),
  DOMESTIC_ABUSE_LETTER_OR_COPY_OF_ASSESSMENT_FROM_A_PUBLIC_BODY_OR_AN_EXPERT_REPO("DV015"),
  DOMESTIC_ABUSE_LETTER_FROM_SECRETARY_OF_STATE_FOR_THE_HOME_DEPARTMENT_CONFIRMING("DV016"),
  DOMESTIC_ABUSE_LETTER_FROM_AN_ORGANISATION_PROVIDING_DOMESTIC_ABUSE_SUPPORT_SERV("DV017"),
  DOMESTIC_ABUSE_EVIDENCE_THAT_THE_PERPETRATOR_IS_OR_HAS_BEEN_UNDER_INVESTIGATION("DV018"),
  DOMESTIC_ABUSE_LETTER_FROM_AN_INDEPENDENT_DOMESTIC_VIOLENCE_ADVISOR_IDVA_OR_AN_I("DV019"),
  CHILD_ABUSE_CONVICTION_CAUTION_OR_BIND_OVER_FOR_CHILD_ABUSE_OFFENCE("CA001"),
  CHILD_ABUSE_ONGOING_CRIMINAL_PROCEEDINGS_FOR_CHILD_ABUSE("CA002"),
  CHILD_ABUSE_APPLICATION_FOR_INJUNCTION_OR_PROTECTIVE_ORDER("CA003"),
  CHILD_PROTECTION_PLAN_IN_PLACE("CA004"),
  CHILD_ABUSE_SOCIAL_SERVICES_LETTER("CA005"),
  CHILD_ABUSE_FINDING_OF_FACT_OF_CHILD_ABUSE("CA006"),
  CHILD_ABUSE_PROHIBITED_STEPS_IN_ADDITION_TO_PROTECTIVE_ORDER_OR_INJUNCTION("CA007"),
  CHILD_ABUSE_POLICE_BAIL("CA008"),
  VICTIM_OF_TRAFFICKING_MODERN_SLAVERY("TR001"),
  INJURY_AT_BIRTH("CN001"),
  FAMILY_CASE_CLIENT_UNDER_18("UA001");

  private final String value;

  ExemptionCriteriaSatisfied(String value) {
    this.value = value;
  }

  @Override
  public String value() {
    return value;
  }
}
