package uk.gov.justice.laa.amend.claim.viewmodels.viewfield;

public enum CrimeLowerOutcomeCode implements FieldOption {
  NO_FURTHER_INSTRUCTIONS("CN01"),
  CHANGE_OF_SOLICITOR("CN02"),
  CLIENT_NOT_A_SUSPECT("CN03"),
  NO_FURTHER_ACTION("CN04"),
  SIMPLE_CAUTION_REPRIMAND_WARNING("CN05"),
  CHARGE_SUMMONS_OR_REPORTED_FOR_SUMMONS("CN06"),
  CONDITIONAL_CAUTION("CN07"),
  FIXED_PENALTY_NOTICE("CN08"),
  RELEASED_NO_BAIL("CN09"),
  BAIL_VARIED_EXTENDED("CN10"),
  BAIL_NOT_VARIED_EXTENDED("CN11"),
  PRE_CHARGE_ENGAGEMENT_AGREED_AND_CONCLUDES_BEFORE_INVESTIGATION_ENDS("CN12"),
  PRE_CHARGE_ENGAGEMENT_NOT_AGREED("CN13"),
  ARREST_WARRANT_ISSUED_ADJOURNED_INDEFINITELY("CP01"),
  CHANGE_OF_SOLICITOR_CP02("CP02"),
  REPRESENTATION_ORDER_WITHDRAWN("CP03"),
  TRIAL_ACQUITTED("CP04"),
  TRIAL_MIXED_VERDICTS("CP05"),
  TRIAL_CONVICTED("CP06"),
  DISCONTINUED_BEFORE_ANY_PLEAS_ENTERED("CP07"),
  DISCONTINUED_AFTER_PLEAS_ENTERED("CP08"),
  GUILTY_PLEA_TO_ALL_CHARGES_PUT_NOT_LISTED_FOR_TRIAL("CP09"),
  GUILTY_PLEA_TO_ALL_CHARGES_PUT_AFTER_CASE_LISTED_FOR_TRIAL("CP10"),
  GUILTY_PLEA_TO_SUBSTITUTE_CHARGES_PUT_AFTER_CASE_LISTED_FOR_TRIAL("CP11"),
  MIX_OF_GUILTY_PLEA_S_AND_DISCONTINUANCE_NOT_LISTED_FOR_TRIAL("CP12"),
  MIX_OF_GUILTY_PLEA_S_AND_DISCONTINUANCE_LISTED_FOR_TRIAL("CP13"),
  CP14("CP14"),
  CP15("CP15"),
  CP16("CP16"),
  EXTRADITION("CP17"),
  CASE_REMITTED_FROM_CROWN_TO_MAGISTRATES_COURT_FOR_SENTENCING("CP18"),
  DEFERRED_SENTENCE("CP19"),
  GRANTED_PRESCRIBED_PROCEEDINGS_ORDER("CP20"),
  PART_GRANTED_PRESCRIBED_PROCEEDINGS_ORDER("CP21"),
  REFUSED_PRESCRIBED_PROCEEDINGS_ORDER("CP22"),
  VARIED_PRESCRIBED_PROCEEDINGS_ORDER("CP23"),
  DISCHARGED_PRESCRIBED_PROCEEDINGS_ORDER("CP24"),
  CP25("CP25"),
  CP26("CP26"),
  CASE_SENT_TO_THE_CROWN_COURT_FOR_TRIAL_ON_AN_EITHER_WAY_OFFENCE("CP27"),
  CASE_SENT_TO_THE_CROWN_COURT_FOR_TRIAL_ON_AN_INDICTABLE_ONLY_OFFENCE("CP28"),
  DISCONTINUED("PL01"),
  CHANGE_OF_SOLICITOR_PL02("PL02"),
  WRITTEN_REPRESENTATIONS_SUCCESSFUL("PL03"),
  WRITTEN_REPRESENTATIONS_REFUSED("PL04"),
  ADJUDICATION_GUILTY_PLEA("PL05"),
  ADJUDICATION_GUILTY_AFTER_HEARING("PL06"),
  ADJUDICATION_NOT_GUILTY_AFTER_HEARING("PL07"),
  ADJUDICATION_CRACKED_HEARING("PL08"),
  PAROLE_PAPER_HEARING("PL09"),
  PAROLE_ORAL_HEARING_SUCCESSFUL("PL10"),
  PAROLE_ORAL_HEARING_NOT_SUCCESSFUL("PL11"),
  PROCEEDED_TO_RECONSIDERATION_JUDICIAL_REVIEW("PL12"),
  NO_FURTHER_ACTION_PL13("PL13"),
  MINIMUM_TERM_REVIEWED_AT_THE_HIGH_COURT("PL14");

  private final String value;

  CrimeLowerOutcomeCode(String value) {
    this.value = value;
  }

  @Override
  public String value() {
    return value;
  }

  @Override
  public String messageKeyPrefix() {
    return "outcomeCode";
  }
}
