spring:
  profiles:
    active: local
  security:
    oauth2:
      client:
        registration:
          my-client:
            client-id: your-client-id
            client-secret: your-client-secret
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          my-client:
            authorization-uri: https://example.com/oauth2/authorize
            token-uri: https://example.com/oauth2/token
            user-info-uri: https://example.com/oauth2/userinfo
            jwk-set-uri: https://example.com/oauth2/jwks

claims-api:
  url: http://localhost:8089
  access-token: ""
microsoft-graph-api:
  url: http://localhost:8089
provider-api:
  url: http://localhost:8089
  access-token: ""
submission:
  high-value-assessment-limit: 50000

feature-flags:
  is-bulk-upload-enabled: true
  is-requested-and-calculated-swap-enabled: true
  is-full-claim-details-enabled: true
  is-claim-amendment-enabled: true
  is-fsp-history-enabled: false

maintenance:
  disable-at-time: 2030-05-29T17:29:00Z
  outage-banner-message: Planned maintenance.

